server:
  port: 8083
spring:
  application:
    name: task-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/devboard}
    username: ${DB_USER:devboard}
    password: ${DB_PASSWORD:devboard}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
app:
  auth-url: ${AUTH_URL:http://localhost:8081}
  project-url: ${PROJECT_URL:http://localhost:8082}
