package com.devboard.project;
import jakarta.persistence.*; import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank; import org.springframework.beans.factory.annotation.Value; import org.springframework.data.jpa.repository.JpaRepository; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.client.RestClient; import java.time.*; import java.util.*;
@Entity @Table(name="projects") class Project { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(nullable=false) Long ownerId; @Column(nullable=false) String title; @Column(length=2000) String description; Instant createdAt=Instant.now(); Instant updatedAt=Instant.now(); Instant deletedAt; }
@Entity @Table(name="collaborators", uniqueConstraints = @UniqueConstraint(columnNames = {"projectId", "userId", "revokedAt"})) class Collaborator { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(nullable=false) Long projectId; @Column(nullable=false) Long userId; Instant createdAt=Instant.now(); Instant revokedAt; }
interface ProjectRepo extends JpaRepository<Project,Long>{List<Project> findByOwnerIdAndDeletedAtIsNullOrderByCreatedAtDesc(Long ownerId); Optional<Project> findByIdAndDeletedAtIsNull(Long id);}
interface CollaboratorRepo extends JpaRepository<Collaborator,Long>{boolean existsByProjectIdAndUserIdAndRevokedAtIsNull(Long projectId,Long userId); List<Collaborator> findByProjectIdAndRevokedAtIsNullOrderByCreatedAtAsc(Long projectId); Optional<Collaborator> findByProjectIdAndUserIdAndRevokedAtIsNull(Long projectId,Long userId); List<Collaborator> findByProjectIdAndRevokedAtIsNull(Long projectId);}
@RestController @RequestMapping("/projects") public class ProjectController {
 private final ProjectRepo repo; private final CollaboratorRepo collaborators; private final RestClient auth; private final RestClient tasks;
 ProjectController(ProjectRepo r,CollaboratorRepo c,@Value("${app.auth-url}")String authUrl,@Value("${app.task-url}")String taskUrl){repo=r;collaborators=c;auth=RestClient.builder().baseUrl(authUrl).build();tasks=RestClient.builder().baseUrl(taskUrl).build();}
 record Input(@NotBlank String title,String description){} record Update(@NotBlank String title,String description){} record CollaboratorInput(Long userId){}

 @PostMapping ResponseEntity<?> create(@RequestHeader("X-API-Key")String key,@Valid @RequestBody Input i){Long u=resolveUserId(key);if(u==null)return unauthorized();Project p=new Project();p.ownerId=u;p.title=i.title();p.description=i.description();repo.save(p);return ResponseEntity.status(201).body(p);}
 @GetMapping ResponseEntity<?> list(@RequestHeader("X-API-Key")String key){Long u=resolveUserId(key);return u==null?unauthorized():ResponseEntity.ok(repo.findByOwnerIdAndDeletedAtIsNullOrderByCreatedAtDesc(u));}
 @GetMapping("/{id}") ResponseEntity<?> get(@RequestHeader("X-API-Key")String key,@PathVariable Long id){Long u=resolveUserId(key);Project p=repo.findByIdAndDeletedAtIsNull(id).orElse(null);if(u==null)return unauthorized();if(p==null)return ResponseEntity.notFound().build();return hasAccess(u,p)?ResponseEntity.ok(p):forbidden();}
 @PutMapping("/{id}") ResponseEntity<?> update(@RequestHeader("X-API-Key")String key,@PathVariable Long id,@Valid @RequestBody Update i){Long u=resolveUserId(key);Project p=repo.findByIdAndDeletedAtIsNull(id).orElse(null);if(u==null)return unauthorized();if(p==null)return ResponseEntity.notFound().build();if(!isOwner(u,p))return forbidden();p.title=i.title();p.description=i.description();p.updatedAt=Instant.now();return ResponseEntity.ok(repo.save(p));}
 @DeleteMapping("/{id}") ResponseEntity<?> delete(@RequestHeader("X-API-Key")String key,@PathVariable Long id){Long u=resolveUserId(key);Project p=repo.findByIdAndDeletedAtIsNull(id).orElse(null);if(u==null)return unauthorized();if(p==null)return ResponseEntity.notFound().build();if(!isOwner(u,p))return forbidden();p.deletedAt=Instant.now();p.updatedAt=Instant.now();repo.save(p);for(Collaborator c:collaborators.findByProjectIdAndRevokedAtIsNull(id)){c.revokedAt=Instant.now();collaborators.save(c);}return ResponseEntity.noContent().build();}

 @PostMapping("/{id}/collaborators") ResponseEntity<?> addCollaborator(@RequestHeader("X-API-Key")String key,@PathVariable Long id,@RequestBody CollaboratorInput input){Long u=resolveUserId(key);Project p=repo.findByIdAndDeletedAtIsNull(id).orElse(null);if(u==null)return unauthorized();if(p==null)return ResponseEntity.notFound().build();if(!isOwner(u,p))return forbidden();if(input.userId()==null)return ResponseEntity.badRequest().body(Map.of("message","userId is required"));if(Objects.equals(input.userId(),p.ownerId))return ResponseEntity.badRequest().body(Map.of("message","Owner is already a member"));if(collaborators.existsByProjectIdAndUserIdAndRevokedAtIsNull(id,input.userId()))return ResponseEntity.status(409).body(Map.of("message","Collaborator already added"));Collaborator c=new Collaborator();c.projectId=id;c.userId=input.userId();collaborators.save(c);return ResponseEntity.status(201).body(c);}
 @GetMapping("/{id}/collaborators") ResponseEntity<?> listCollaborators(@RequestHeader("X-API-Key")String key,@PathVariable Long id){Long u=resolveUserId(key);Project p=repo.findByIdAndDeletedAtIsNull(id).orElse(null);if(u==null)return unauthorized();if(p==null)return ResponseEntity.notFound().build();if(!hasAccess(u,p))return forbidden();return ResponseEntity.ok(collaborators.findByProjectIdAndRevokedAtIsNullOrderByCreatedAtAsc(id));}
 @DeleteMapping("/{id}/collaborators/{userId}") ResponseEntity<?> removeCollaborator(@RequestHeader("X-API-Key")String key,@PathVariable Long id,@PathVariable Long userId){Long u=resolveUserId(key);Project p=repo.findByIdAndDeletedAtIsNull(id).orElse(null);if(u==null)return unauthorized();if(p==null)return ResponseEntity.notFound().build();if(!isOwner(u,p))return forbidden();Collaborator c=collaborators.findByProjectIdAndUserIdAndRevokedAtIsNull(id,userId).orElse(null);if(c==null)return ResponseEntity.notFound().build();c.revokedAt=Instant.now();collaborators.save(c);return ResponseEntity.noContent().build();}

 @GetMapping("/{id}/export") ResponseEntity<?> export(@RequestHeader("X-API-Key")String key,@PathVariable Long id){Long u=resolveUserId(key);Project p=repo.findByIdAndDeletedAtIsNull(id).orElse(null);if(u==null)return unauthorized();if(p==null)return ResponseEntity.notFound().build();if(!hasAccess(u,p))return forbidden();List<?> taskList;try{taskList=tasks.get().uri("/internal/projects/{id}/tasks",id).retrieve().body(List.class);}catch(Exception e){taskList=List.of();}Map<String,Object> out=new LinkedHashMap<>();out.put("project",p);out.put("tasks",taskList);out.put("exportedAt",Instant.now());return ResponseEntity.ok(out);}

 @GetMapping("/internal/{id}/owner") ResponseEntity<?> owner(@PathVariable Long id){return repo.findByIdAndDeletedAtIsNull(id).<ResponseEntity<?>>map(p->ResponseEntity.ok(Map.of("ownerId",p.ownerId))).orElseGet(()->ResponseEntity.notFound().build());}
 @GetMapping("/internal/{id}/access/{userId}") ResponseEntity<?> access(@PathVariable Long id,@PathVariable Long userId){Project p=repo.findByIdAndDeletedAtIsNull(id).orElse(null);if(p==null)return ResponseEntity.notFound().build();boolean allowed=Objects.equals(p.ownerId,userId)||collaborators.existsByProjectIdAndUserIdAndRevokedAtIsNull(id,userId);return ResponseEntity.ok(Map.of("allowed",allowed));}

 private boolean isOwner(Long userId,Project p){return Objects.equals(p.ownerId,userId);} private boolean hasAccess(Long userId,Project p){return isOwner(userId,p)||collaborators.existsByProjectIdAndUserIdAndRevokedAtIsNull(p.id,userId);} private Long resolveUserId(String key){try{Map<?,?> m=auth.get().uri("/auth/internal/api-keys/validate").header("X-API-Key",key).retrieve().body(Map.class);return ((Number)m.get("userId")).longValue();}catch(Exception e){return null;}} private ResponseEntity<?> unauthorized(){return ResponseEntity.status(401).body(Map.of("message","Valid X-API-Key required"));} private ResponseEntity<?> forbidden(){return ResponseEntity.status(403).body(Map.of("message","Project access denied"));}
}
