package com.devboard.task;
import jakarta.persistence.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.data.domain.*; import org.springframework.data.jpa.repository.JpaRepository; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.client.RestClient; import java.time.*; import java.util.*;
@Entity @Table(name="tasks") class Task { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(nullable=false) Long projectId; @Column(nullable=false) String title; @Column(length=2000) String description; @Enumerated(EnumType.STRING) Status status=Status.TODO; @Enumerated(EnumType.STRING) Priority priority=Priority.MEDIUM; LocalDate dueDate; Instant createdAt=Instant.now(); Instant updatedAt=Instant.now(); Instant deletedAt; }
enum Status { TODO, IN_PROGRESS, DONE } enum Priority { LOW, MEDIUM, HIGH }
interface TaskRepo extends JpaRepository<Task,Long>{Page<Task> findByProjectIdAndDeletedAtIsNullOrderByCreatedAtDesc(Long projectId,Pageable p); Optional<Task> findByIdAndDeletedAtIsNull(Long id); List<Task> findByProjectIdAndDeletedAtIsNullOrderByCreatedAtDesc(Long projectId);}
@RestController public class TaskController { private final TaskRepo repo; private final RestClient auth,projects;
 TaskController(TaskRepo r,@Value("${app.auth-url}")String a,@Value("${app.project-url}")String p){repo=r;auth=RestClient.builder().baseUrl(a).build();projects=RestClient.builder().baseUrl(p).build();}
 record Create(@NotBlank String title,String description,Priority priority,LocalDate dueDate){} record Update(@NotBlank String title,String description,Status status,Priority priority,LocalDate dueDate){}
 @PostMapping("/projects/{projectId}/tasks") ResponseEntity<?> create(@RequestHeader("X-API-Key")String k,@PathVariable Long projectId,@Valid @RequestBody Create i){Long u=user(k);if(u==null)return unauthorized();if(!hasAccess(u,projectId))return forbidden();Task t=new Task();t.projectId=projectId;t.title=i.title();t.description=i.description();if(i.priority()!=null)t.priority=i.priority();t.dueDate=i.dueDate();return ResponseEntity.status(201).body(repo.save(t));}
 @GetMapping("/projects/{projectId}/tasks") ResponseEntity<?> list(@RequestHeader("X-API-Key")String k,@PathVariable Long projectId,@RequestParam(defaultValue="0")@Min(0) int page,@RequestParam(defaultValue="20")@Min(1)@Max(100) int size){Long u=user(k);if(u==null)return unauthorized();if(!hasAccess(u,projectId))return forbidden();return ResponseEntity.ok(repo.findByProjectIdAndDeletedAtIsNullOrderByCreatedAtDesc(projectId,PageRequest.of(page,size)));}
 @PutMapping("/tasks/{id}") ResponseEntity<?> update(@RequestHeader("X-API-Key")String k,@PathVariable Long id,@Valid @RequestBody Update i){Task t=repo.findByIdAndDeletedAtIsNull(id).orElse(null);if(t==null)return ResponseEntity.notFound().build();Long u=user(k);if(u==null)return unauthorized();if(!hasAccess(u,t.projectId))return forbidden();t.title=i.title();t.description=i.description();if(i.status()!=null)t.status=i.status();if(i.priority()!=null)t.priority=i.priority();t.dueDate=i.dueDate();t.updatedAt=Instant.now();return ResponseEntity.ok(repo.save(t));}
 @DeleteMapping("/tasks/{id}") ResponseEntity<?> delete(@RequestHeader("X-API-Key")String k,@PathVariable Long id){Task t=repo.findByIdAndDeletedAtIsNull(id).orElse(null);if(t==null)return ResponseEntity.notFound().build();Long u=user(k);if(u==null)return unauthorized();if(!hasAccess(u,t.projectId))return forbidden();t.deletedAt=Instant.now();t.updatedAt=Instant.now();repo.save(t);return ResponseEntity.noContent().build();}
 @GetMapping("/internal/projects/{projectId}/tasks") ResponseEntity<?> internalList(@PathVariable Long projectId){return ResponseEntity.ok(repo.findByProjectIdAndDeletedAtIsNullOrderByCreatedAtDesc(projectId));}

 private boolean hasAccess(Long userId,Long projectId){try{Map<?,?> m=projects.get().uri("/projects/internal/{id}/access/{userId}",projectId,userId).retrieve().body(Map.class);Object allowed=m==null?null:m.get("allowed");return Boolean.TRUE.equals(allowed);}catch(Exception e){return false;}}
 private Long user(String k){try{Map<?,?> m=auth.get().uri("/auth/internal/api-keys/validate").header("X-API-Key",k).retrieve().body(Map.class);return ((Number)m.get("userId")).longValue();}catch(Exception e){return null;}}
 private ResponseEntity<?> unauthorized(){return ResponseEntity.status(401).body(Map.of("message","Valid X-API-Key required"));}
 private ResponseEntity<?> forbidden(){return ResponseEntity.status(403).body(Map.of("message","Project access denied"));}
}
